// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

<<<<<<< HEAD
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://jdqupzhfyqqvfclpljpe.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkcXVwemhmeXFxdmZjbHBsanBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MDQ2MzMsImV4cCI6MjA5MTM4MDYzM30.Leljodl_SBEH8WPUTksWa3z4jh8w_-OkIauLaPwE_Ws';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Supabase environment variables missing');
}
=======
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
>>>>>>> 9e3f45b0ee34d0c9b3b0b17417f24ac9ba002cd8

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
<<<<<<< HEAD
  },
  global: {
    fetch: async (...args) => {
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 15000);
        const response = await fetch(args[0], { ...args[1], signal: controller.signal });
        clearTimeout(timeoutId);
        return response;
      } catch (error) {
        console.warn('Fetch timeout or error:', error);
        throw error;
      }
    }
  }
});
=======
  }
});
>>>>>>> 9e3f45b0ee34d0c9b3b0b17417f24ac9ba002cd8
